# Generated by Django 3.0.7 on 2021-01-02 14:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stories', '0002_auto_20210102_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='loves',
            field=models.ManyToManyField(blank=True, related_name='loves', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='views', to=settings.AUTH_USER_MODEL),
        ),
    ]
