# Generated by Django 3.0.7 on 2021-01-04 18:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_auto_20210102_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='arr',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), default=list, size=10),
        ),
    ]
