# Generated by Django 3.0.7 on 2021-01-17 14:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0010_auto_20210113_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='story',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), default=list, size=30),
        ),
        migrations.AlterField(
            model_name='story',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
