# Generated by Django 3.0.7 on 2021-01-02 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='joined',
            field=models.DateField(auto_now_add=True),
        ),
    ]
